<?php
use Attendance\Entity\Entry;

$title = 'Termin bearbeiten';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?> <small><?php echo $sheet->name . ' ' . $sheet->year . ', ' . $sheet->band;?></small></h1>

<?php
$form->setAttribute('action', $this->url('attendanceEventEdit', array('id' => $id, 'eventId' => $eventId)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('date'));
        echo $this->formRow($form->get('name'));
        ?>
        <hr>
        <?php
        foreach ($index as $registerId => $registerData) {
            if (empty($registerData['members'])) {
                continue;
            }
            echo '<h2>' . $registerData['registerName'] . '</h2>';
            foreach ($registerData['members'] as $member) {
                $entry = $entries[$member->id];
                echo '
                <div class="form-group ">
                    <label class="col-sm-3 control-label">' . $member->lastname . ' ' . $member->firstname . '</label>
                    <div class="col-sm-9">
                        <div class="btn-group" data-toggle="buttons">
                            <label class="btn btn-default' . ($entry->status == Entry::STATUS_PRESENT ? ' active' : '') . '">
                                <input type="radio" value="' . Entry::STATUS_PRESENT . '" name="entries[' . $member->id . ']" autocomplete="off"' . ($entry->status == Entry::STATUS_PRESENT ? ' checked' : '') . '> <i class="fa fa-check fa-fw"></i>
                            </label>
                            <label class="btn btn-default' . ($entry->status == Entry::STATUS_ABSENT ? ' active' : '') . '">
                                <input type="radio" value="' . Entry::STATUS_ABSENT . '" name="entries[' . $member->id . ']" autocomplete="off"' . ($entry->status == Entry::STATUS_ABSENT ? ' checked' : '') . '> <i class="fa fa-close fa-fw"></i>
                            </label>
                            <label class="btn btn-default' . ($entry->status == Entry::STATUS_EXCUSED ? ' active' : '') . '">
                                <input type="radio" value="' . Entry::STATUS_EXCUSED . '" name="entries[' . $member->id . ']" autocomplete="off"' . ($entry->status == Entry::STATUS_EXCUSED ? ' checked' : '') . '> <i class="fa fa-info fa-fw"></i>
                            </label>
                        </div>
                    </div>
                </div>';
            }
        }
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('attendance'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>