<?php
use Attendance\Entity\Entry;

$title = 'Anwesenheitsliste';
$this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
</h1>

<h2><?php echo $this->escapeHtml($sheet->name . ' ' . $sheet->year . ', ' . $sheet->band);?></h2>

<script>
$(function() {
   $('.rotated-header-row').each(function(){
       var row        = $(this);
       var headerCols = row.find('.rotated-header-col');
       var maxWidth   = 0;

       headerCols.each(function() {
           // wrap structure
           $(this).wrapInner('<div class="rotated-header-container"><div class="rotated-header-block"></div></div>');

           // find max width of header content
           var w = $(this).find('.rotated-header-block').width();
           var h = $(this).find('.rotated-header-block').height();
           if (w > maxWidth) {
               maxWidth = w;
           }
           var d = (42 - h) / 4;
           $(this).find('.rotated-header-block').css({
               'transform-origin': '' + d + 'px ' + (-1 * d) + 'px'
           });
       });
       headerCols.css({'height': maxWidth + 5}); // min-height funktioniert hier nicht. WTF.

       headerCols.find('.rotated-header-container').css({
           position : 'relative',
           height   : 0,
           width    : 42
       });
       headerCols.find('.rotated-header-block').css({
           transform: 'rotate(-90deg)',
           width: maxWidth + 5
       });
   });
});
</script>

<table class="table table-striped table-hover table-condensed" style="width:auto;">
    <thead>
	    <tr class="rotated-header-row">
            <th>&nbsp;</th>
            <?php foreach ($sheet->events as $event) { ?>
                <th class="rotated-header-col" style="line-height:1.25">
                <?php
                    echo '<a href="' . $this->url('attendanceEventEdit', array('id' => $sheet->id, 'eventId' => $event->id)) . '">';
                    echo $event->date->format('d.m.');
                    echo '</a>';
                    if ($event->name) {
                        echo '<br><small class="text-muted">' . $this->escapeHtml($event->name) . '</small>';
                    }
                ?>
                </th>
            <?php } ?>
	    </tr>
    </thead>
    <?php
    foreach ($index as $registerData) {
        if (empty($registerData['members'])) {
            continue;
        }
        ?>
        <tr>
            <th colspan="<?php echo count($sheet->events) + 1; ?>"><?php echo $this->escapeHtml($registerData['registerName']); ?></th>
        </tr>
        <?php
        foreach ($registerData['members'] as $member) {
            echo '
            <tr>
                <td style="white-space:nowrap;">' .  $this->escapeHtml($member->lastname . ' ' . $member->firstname) . '</td>';
            foreach ($sheet->events as $event) {
                $status = null;
                if (isset($entries[$event->id][$member->id])) {
                    $status = $entries[$event->id][$member->id]->status;
                }
                if ($status === Entry::STATUS_PRESENT) {
                    echo '<td class="text-center success"><i class="fa fa-check fa-lg text-success"></i></td>';
                }
                if ($status === Entry::STATUS_ABSENT) {
                    echo '<td class="text-center danger"><i class="fa fa-close fa-lg text-danger"></i></td>';
                }
                if ($status === Entry::STATUS_EXCUSED) {
                    echo '<td class="text-center danger"><i class="fa fa-info fa-lg text-danger"></i></td>';
                }
                if ($status === null) {
                    echo '<td class="">&nbsp;</td>';
                }
            }
            echo '
            </tr>';
        }
    }
    ?>
</table>
