<?php
use Attendance\Entity\Entry;

$title = 'Anwesenheitsliste';
$this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
</h1>

<h2><?php echo $this->escapeHtml($sheet->name . ' ' . $sheet->year . ', ' . $sheet->band);?></h2>

<table class="table table-striped table-hover table-condensed">
    <thead>
	    <tr>
            <th width="0%">&nbsp;</th>
            <?php foreach ($sheet->events as $event) { ?>
                <th class="text-center">
                <?php
                    echo '<a href="' . $this->url('attendanceEventEdit', array('id' => $sheet->id, 'eventId' => $event->id)) . '">';
                    echo $event->date->format('d.m.');
                    echo '</a>';
                    if ($event->name) {
                        echo '<br><small class="text-muted">' . $this->escapeHtml($event->name) . '</small>';
                    }
                ?>
                </th>
            <?php } ?>
	    </tr>
    </thead>
    <?php
    foreach ($index as $registerData) {
        if (empty($registerData['members'])) {
            continue;
        }
        ?>
        <tr>
            <th colspan="<?php echo count($sheet->events) + 1; ?>"><?php echo $this->escapeHtml($registerData['registerName']); ?></th>
        </tr>
        <?php
        foreach ($registerData['members'] as $member) {
            echo '
            <tr>
                <td style="white-space:nowrap;">' .  $this->escapeHtml($member->lastname . ' ' . $member->firstname) . '</td>';
            foreach ($sheet->events as $event) {
                $status = null;
                if (isset($entries[$event->id][$member->id])) {
                    $status = $entries[$event->id][$member->id]->status;
                }
                if ($status === Entry::STATUS_PRESENT) {
                    echo '<td class="text-center success"><i class="fa fa-check fa-lg text-success"></i></td>';
                }
                if ($status === Entry::STATUS_ABSENT) {
                    echo '<td class="text-center danger"><i class="fa fa-close fa-lg text-danger"></i></td>';
                }
                if ($status === Entry::STATUS_EXCUSED) {
                    echo '<td class="text-center danger"><i class="fa fa-info fa-lg text-danger"></i></td>';
                }
                if ($status === null) {
                    echo '<td class="">&nbsp;</td>';
                }
            }
            echo '
            </tr>';
        }
    }
    ?>
</table>
