<?php
 $title = 'Login';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('login'));
 $form->prepare();

 echo $this->form()->openTag($form);
 ?>
 <div class="row">
    <div class="col-sm-6">
    <?php
        echo $this->formRow($form->get('username'));
        echo $this->formRow($form->get('password'));
        echo $this->formRow($form->get('submit'));
    ?>
    </div>
 </div>
<?php
 echo $this->form()->closeTag();
 ?>