<?php
$title = 'Noten bearbeiten';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('sheetmusicEdit', array('id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
        $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('title'));
        echo $this->formRow($form->get('composer'));
        echo $this->formRow($form->get('arranger'));
        echo $this->formRow($form->get('publisher'));
        echo $this->formRow($form->get('year'));
        echo $this->formRow($form->get('genre'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('isAway'));
        echo $this->formRow($form->get('isScanned'));
        echo $this->formRow($form->get('archivedAt'));
        echo $this->formRow($form->get('isUnusable'));
        echo $this->formRow($form->get('comment'));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('sheetmusic'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>