<?php
$title = 'Noten';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('sheetmusicEdit', array('id' => 0));?>">Neues Stück eingeben</a>
</p>

<?php
$form->setAttribute('action', $this->url('sheetmusic'));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="well well-sm">
    <div class="row">
        <div class="col-md-6">
            <?php
            echo $this->formRow($form->get('title'));
            echo $this->formRow($form->get('composer-arranger'));
            echo $this->formRow($form->get('publisher'));
            ?>
        </div>
        <div class="col-md-6">
            <?php
            echo $this->formRow($form->get('genre'));
            echo $this->formRow($form->get('isAway'));
            echo $this->formRow($form->get('isScanned'));
            echo $this->formRow($form->get('submit'));
            ?>
        </div>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>

<table class="table table-striped table-hover">
	<tr>
        <th>Titel</th>
        <th>Komponist</th>
        <th>Arrangeur</th>
		<th>Genre</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($pieces as $piece) { ?>
		<tr>
            <td><?php echo $this->escapeHtml($piece->title);?></td>
            <td><?php echo $this->escapeHtml($piece->composer);?></td>
            <td><?php echo $this->escapeHtml($piece->arranger);?></td>
			<td><?php echo $this->escapeHtml($piece->genre->name);?></td>
			<td>
				<a href="<?php echo $this->url('sheetmusicEdit', array('id' => $piece->id));?>">Edit</a>
				<a href="<?php echo $this->url('sheetmusic');?>">Delete</a>
			</td>
		</tr>
		<?php } ?>
</table>

<?php
echo $this->paginationControl($pieces,
    'Sliding',
    '_partials/paginator', array(
        'route' => 'sheetmusic',
        'route_params' => array()
    )
);
