<?php
$title = 'Termin bearbeiten';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('calendarEdit', array('action' => 'edit', 'id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('date'));
        echo $this->formRow($form->get('dateTo'));
        echo $this->formRow($form->get('beginTime'));
        echo $this->formRow($form->get('appointmentTime'));
        echo $this->formRow($form->get('city'));
        echo $this->formRow($form->get('location'));
        echo $this->formRow($form->get('comment'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('type'));
        echo $this->formRow($form->get('band'));
        echo $this->formRow($form->get('clothing'));
        echo $this->formRow($form->get('status'));
        ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
    	<h2>Anzeige</h2>
        <?php
        echo $this->formRow($form->get('showOnHomepage'));
        echo $this->formRow($form->get('homepageText'));
        echo $this->formRow($form->get('showInGoogleCalendar'));
        echo $this->formRow($form->get('showInBoard'));
        echo $this->formRow($form->get('boardText'));
        ?>
    </div>
    <div class="col-sm-6">
    	<h2>Verrechnung</h2>
        <?php
        echo $this->formRow($form->get('accountingInfo'));
        echo $this->formRow($form->get('accountingAddress'));
        ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('calendar'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>

<script>
$(function() {
	var linkElement = $('<a href="#">Standard-Text erzeugen</a>');
	linkElement.click(function(event) {
		event.preventDefault();
		
		s = $('[name="name"]').val();
		s += "\r\n" + 'Datum: ' + $('[name="date"]').val();
		if ($('[name="dateTo"]').val()) {
			s += "\r\n" + 'Bis: ' + $('[name="dateTo"]').val();
		}
		if ($('[name="beginTime"]').val()) {
			s += "\r\n" + 'Beginn: ' + $('[name="beginTime"]').val();
		}
		if ($('[name="appointmentTime"]').val()) {
			s += "\r\n" + 'Treffpunkt: ' + $('[name="appointmentTime"]').val();
		}
		if ($('[name="city"]').val()) {
			s += "\r\n" + 'Ort: ' + $('[name="city"]').val();
		}
		if ($('[name="location"]').val()) {
			s += ' (' + $('[name="location"]').val() + ')';
		}
		$('[name="boardText"]').val(s);
	});
	
	$('[name="boardText"] + .help-block').append(' | ').append(linkElement);
});
</script>