<?php
$title = 'Termin bearbeiten';
$this->headTitle($title);
?>


<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('calendarEdit', array('action' => 'edit', 'id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('date'));
        echo $this->formRow($form->get('dateTo'));
        echo $this->formRow($form->get('beginTime'));
        echo $this->formRow($form->get('appointmentTime'));
        echo $this->formRow($form->get('city'));
        echo $this->formRow($form->get('location'));
        echo $this->formRow($form->get('comment'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('type'));
        echo $this->formRow($form->get('band'));
        echo $this->formRow($form->get('status'));
        ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <h3>Homepage</h3>
        <?php
        echo $this->formRow($form->get('showOnHomepage'));
        echo $this->formRow($form->get('homepageText'));
        ?>
    </div>
    <div class="col-sm-6">
        <h3>Board</h3>
        <?php
        echo $this->formRow($form->get('showInBoard'));
        echo $this->formRow($form->get('boardText'));
        ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('calendar'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
