<?php
$title = 'Instrument bearbeiten';
$this->headTitle($title);
?>

<?php echo $this->getTabnav($tabnav); ?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('instrumentEdit', array('id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
        $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('category'));
        echo $this->formRow($form->get('brand'));
        echo $this->formRow($form->get('variant'));
        echo $this->formRow($form->get('serialNumber'));
        echo $this->formRow($form->get('buyDate'));
        echo $this->formRow($form->get('outDate'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('insurance'));
        echo $this->formRow($form->get('comment'));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('instruments'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
echo $this->form()->closeTag();
