<?php
$title = 'Dokument hochladen/bearbeiten';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('documentEdit', array('id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('category'));
        echo $this->formRow($form->get('upload'));
        echo $this->formRow($form->get('description'));
        echo $this->formRow($form->get('referenceDate'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        echo $this->formRow($form->get('comment'));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('sheetmusic'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>