<?php
$title = 'Dokumente';
$this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
	<a class="btn btn-success pull-right" href="<?php echo $this->url('documentEdit', array('id' => 0));?>">Neues Dokument hochladen</a>
</h1>

<?php
$form->setAttribute('action', $this->url('documents'));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="well">
    <div class="row">
        <div class="col-md-6">
            <?php
            echo $this->formRow($form->get('category'));
            ?>
        </div>
        <div class="col-md-6">
            <?php
            echo $this->formRow($form->get('description'));
            echo $this->formRow($form->get('submit'));
            ?>
        </div>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>

<table class="table table-striped table-hover">
    <thead>
	    <tr>
            <th>Kategorie</th>
            <th>Hochgeladen am</th>
            <th>Beschreibung</th>
		    <th>&nbsp;</th>
	    </tr>
    </thead>
	<?php foreach ($documents as $document) { ?>
		<tr>
            <td><?php echo $this->escapeHtml($document->category->name);?></td>
            <td><?php echo $this->escapeHtml($document->uploadDate->format('d.m.Y'));?></td>
            <td>
                <a href="<?php echo $this->url('documentDownload', array('hash' => $document->hash));?>">
                    <i class="fa fa-download fa-fw"></i>
                    <?php echo $this->escapeHtml($document->description);?>
                </a>
            </td>
            <td>
				<a href="<?php echo $this->url('documentEdit', array('id' => $document->id));?>">Bearbeiten</a>
			</td>
		</tr>
		<?php } ?>
</table>

<?php
echo $this->paginationControl($documents,
    'Sliding',
    '_partials/paginator', array(
        'route' => 'documents',
        'route_params' => array()
    )
);
