<?php
$title = 'Mitglieder';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('memberEdit', array('id' => 0));?>">Neues Mitglied hinzufügen</a>
</p>

<?php
$form->setAttribute('action', $this->url('members', array('action' => 'index')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="well well-sm">
    <div class="row">
        <div class="col-md-6">
            <?php
            echo $this->formRow($form->get('namesearch'));
            ?>
        </div>
        <div class="col-md-6">
            <?php
            echo $this->formRow($form->get('submit'));
            ?>
        </div>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>

<table class="table table-striped table-hover">
	<tr>
        <th width="20%">Nachname</th>
        <th width="20%">Vorname</th>
        <th width="20%">E-Mail</th>
		<th width="20%">Telefonnummer(n)</th>
		<th width="20%">&nbsp;</th>
	</tr>
    <?php foreach ($members as $member) { ?>
        <tr>
            <td><?php echo $this->escapeHtml($member->lastname);?></td>
            <td><?php echo $this->escapeHtml($member->firstname);?></td>
            <td><?php echo $this->escapeHtml($member->email1);?></td>
            <td><?php echo $this->escapeHtml($member->phone1);?></td>
			<td>
                <a href="<?php echo $this->url('memberEdit', array('id' => $member->id));?>">Edit</a>
                <a href="<?php echo $this->url('memberMedals', array('id' => $member->id));?>">Verleih.</a>
                <a href="<?php echo $this->url('memberWorkshops', array('id' => $member->id));?>">Kurse</a>
				<a href="<?php echo $this->url('members');?>">Delete</a>
			</td>
		</tr>
    <?php } ?>
</table>
