<?php
$title = 'Abzeichen eintragen';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($member->firstname . ' ' . $member->lastname); ?></h1>

<?php echo $this->getTabnav($tabnav); ?>

<h2>Verleihung <?php echo $form->getObject()->id === null ? 'eintragen' : 'bearbeiten'; ?></h2>

<?php
$form->setAttribute('action', $this->url('memberMedals', array('id' => $id, 'connId' => $connId)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
            echo $this->formRow($form->get('medal'));
            echo $this->formRow($form->get('year'));
            echo $this->formRow($form->get('infos'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('members'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();

echo '<h2>Verleihungen</h2>';

if (count($member->member2medals)) {
    ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Abzeichen</th>
                <th>Jahr</th>
                <th>Zusatzinfos</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <?php foreach ($member->member2medals as $connector) { ?>
            <tr>
                <td>
                    <?php echo $connector->medal->name; ?>
                </td>
                <td>
                    <?php echo $connector->year; ?>
                </td>
                <td>
                    <?php echo $connector->infos; ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('memberMedals', array('id' => $id, 'connId' => $connector->id)); ?>">Bearbeiten</a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php
}
