<?php
$title = 'Mitgliedschaft eintragen';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($member->firstname . ' ' . $member->lastname); ?></h1>

<?php echo $this->getTabnav($tabnav); ?>

<h2>Mitgliedschaft <?php echo $form->getObject()->id === null ? 'eintragen' : 'bearbeiten'; ?></h2>

<?php
$form->setAttribute('action', $this->url('memberMembership', array('id' => $id, 'connId' => $connId)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
            echo $this->formRow($form->get('beginDate'));
            echo $this->formRow($form->get('endDate'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('members'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();

echo '<h2>Bisherige Mitgliedschaften</h2>';

if (count($member->member2bands)) {
    ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Eintritt</th>
                <th>Austritt</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <?php foreach ($member->memberships as $connector) { ?>
            <tr>
                <td>
                    <?php echo $connector->beginDate->format('d.m.Y'); ?>
                </td>
                <td>
                    <?php echo $connector->endDate ? $connector->endDate->format('d.m.Y') : '&nbsp;'; ?>
                </td>
                <td>
                    <a class="btn btn-primary btn-xs" href="<?php echo $this->url('memberMembership', array('id' => $id, 'connId' => $connector->id)); ?>">Bearbeiten</a>
                    <button type="button" class="btn btn-danger btn-xs js-button-delete" data-href="<?php echo $this->url('memberMembership', array('id' => $id, 'connId' => $connector->id)); ?>">Löschen</button>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php
}
?>

<script>
    $(function() {
        $('.js-button-delete').click(function() {
            var target = $(this).data('href');
            $('<form action="' + target + '" method="post"><input type="hidden" name="do" value="delete"></form>').appendTo('body').submit();
        });
    });
</script
