<?php
$title = 'Kursbesuch eintragen';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($member->firstname . ' ' . $member->lastname); ?></h1>

<?php echo $this->getTabnav($tabnav); ?>

<h2>Kursbesuch <?php echo $form->getObject()->id === null ? 'eintragen' : 'bearbeiten'; ?></h2>

<?php
$form->setAttribute('action', $this->url('memberWorkshops', array('id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
            echo $this->formRow($form->get('workshop'));
            echo $this->formRow($form->get('infos'));
        ?>
    </div>
    <div class="col-sm-6">
        <?php
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('members'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();

echo '<h2>Besuchte Kurse</h2>';

if (count($member->member2workshops)) {
    ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Datum</th>
                <th>Kurs</th>
                <th>Ort</th>
                <th>Zusatzinfos</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <?php foreach ($member->member2workshops as $connector) { ?>
            <tr>
                <td>
                    <?php
                    echo $connector->workshop->beginDate->format('d.m.Y');
                    if ($connector->workshop->endDate) {
                        echo ' &ndash; ' . $connector->workshop->endDate->format('d.m.Y');
                    }
                    ?>
                </td>
                <td>
                    <?php echo $connector->workshop->name; ?>
                </td>
                <td>
                    <?php echo $connector->workshop->city; ?>
                </td>
                <td>
                    <?php echo $connector->infos; ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('memberWorkshops', array('id' => $id, 'connId' => $connector->id)); ?>">Bearbeiten</a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php
}
