<?php
$title = 'Kursbesuch eintragen';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($member->firstname . ' ' . $member->lastname); ?></h1>

<?php echo $this->getTabnav($tabnav); ?>

<h2>Kursbesuch <?php echo $form->getObject()->id === null ? 'eintragen' : 'bearbeiten'; ?></h2>

<?php
$form->setAttribute('action', $this->url('memberWorkshops', array('id' => $id, 'connId' => $connId)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">
        <?php
            echo $this->formRow($form->get('workshop'));
            echo $this->formRow($form->get('year'));
            echo $this->formRow($form->get('infos'));
        ?>
    </div>
	<div class="col-sm-6">
		<div class="form-group">
			<div class="col-sm-12">
				<p class="form-control-static"><a href="<?php echo $this->url('workshopEdit', array('id' => 0)); ?>" target="_blank">Neuer Kurs...</a></p>
			</div>
		</div>    
		<?php
        ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <a href="<?php echo $this->url('members'); ?>" class="btn btn-default">Abbrechen</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();

echo '<h2>Besuchte Kurse</h2>';

if (count($member->member2workshops)) {
    ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Jahr</th>
                <th>Kurs</th>
                <th>Zusatzinfos</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <?php foreach ($member->member2workshops as $connector) { ?>
            <tr>
                <td>
                    <?php echo $connector->year; ?>
                </td>
                <td>
                    <?php echo $connector->workshop->name; ?>
                </td>
                <td>
                    <?php echo $connector->infos; ?>
                </td>
                <td>
                    <a class="btn btn-primary btn-xs" href="<?php echo $this->url('memberWorkshops', array('id' => $id, 'connId' => $connector->id)); ?>">Bearbeiten</a>
                    <button type="button" class="btn btn-danger btn-xs js-button-delete" data-href="<?php echo $this->url('memberWorkshops', array('id' => $id, 'connId' => $connector->id)); ?>">Löschen</button>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php
}
?>

<script>
    $(function() {
        $('.js-button-delete').click(function() {
            var target = $(this).data('href');
            $('<form action="' + target + '" method="post"><input type="hidden" name="do" value="delete"></form>').appendTo('body').submit();
        });
    });
</script
