<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vereinsverwaltung')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Josefin+Sans|Oswald')
        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/vendor/datepicker/datepicker3.css')
        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/css/bootstrap.min.css'); ?>

        <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/application.js')
        ->prependFile($this->basePath() . '/vendor/datepicker/locales/bootstrap-datepicker.de.js')
        ->prependFile($this->basePath() . '/vendor/datepicker/bootstrap-datepicker.js')
        ->prependFile($this->basePath() . '/js/twb3bugfix.js')
        ->prependFile($this->basePath() . '/vendor/bootstrap/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/vendor/jquery/jquery-2.1.1.min.js')
        //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
        //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9'))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-home fa-fw fa-lg"></i> Home</a></li>

                        <?php if ($this->isAllowed('Members\Controller\Member')) { ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-group fa-fw fa-lg"></i> Mitglieder <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('members'); ?>">Personenliste</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('workshops'); ?>">Kurse</a></li>
                                <li><a href="<?php echo $this->url('medals'); ?>">Abzeichen</a></li>
                            </ul>
                        </li>
                        <?php } ?>

                        <?php if ($this->isAllowed('Attendance\Controller\Sheet')) { ?>
                        <li><a href="<?php echo $this->url('attendance') ?>"><i class="fa fa-table fa-fw fa-lg"></i> Anwesenheit</a></li>
                        <?php } ?>

                        <?php if ($this->isAllowed('Calendar\Controller\Calendar')) { ?>
                        <li><a href="<?php echo $this->url('calendar') ?>"><i class="fa fa-calendar fa-fw fa-lg"></i> Termine</a></li>
                        <?php } ?>

                        <?php if ($this->isAllowed('Instruments\Controller\Instrument')) { ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-tags fa-fw fa-lg"></i> Instrumente <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('instruments'); ?>">Liste</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('instrumentCategories'); ?>">Kategorien</a></li>
                            </ul>
                        </li>
                        <?php } ?>

                        <?php if ($this->isAllowed('Sheetmusic\Controller\Sheetmusic')) { ?>
                        <li><a href="<?php echo $this->url('sheetmusic'); ?>"><i class="fa fa-music fa-fw fa-lg"></i> Noten</a></li>
                        <?php } ?>

                        <?php if ($this->isAllowed('Documents\Controller\Document')) { ?>
                        <li><a href="<?php echo $this->url('documents'); ?>"><i class="fa fa-file fa-fw fa-lg"></i> Dokumente</a></li>
                        <?php } ?>
                    </ul>

                    <?php
                    $user = $this->identity();
                    if ($user) {
                        ?>
                        <p class="navbar-text navbar-right"><a href="<?php echo $this->url('logout'); ?>" class="navbar-link">Logout <i class="fa fa-sign-out fa-fw fa-lg"></i></a></p>
                        <?php
                    }
                    ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php
            $flash = $this->flashMessenger();
            echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
            echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
            echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            ?>
            
            <?php echo $this->content; ?>

            <hr>

            <footer>
                <p><?php echo $this->customization('footer_line'); ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
