<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vereinsverwaltung')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/print.css', 'screen,print')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Josefin+Sans|Oswald', 'screen,print')
        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', 'screen,print')
        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/css/bootstrap.min.css', 'screen,print'); ?>

        <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bmk.js')
        ->prependFile($this->basePath() . '/js/application.js')
        ->prependFile($this->basePath() . '/vendor/bootstrap/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/vendor/jquery/jquery-2.1.1.min.js')
        ; ?>

    </head>
    <body>
        <div class="container <?php if ($this->format === 'A3') { echo 'a3'; } ?>">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
