<?php
$title = 'Abzeichen';
$this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
    <a class="btn btn-success pull-right" href="<?php echo $this->url('medalEdit', array('id' => 0));?>">Neues Abzeichen hinzufügen</a>
</h1>

<table class="table table-striped table-hover">
    <thead>
	    <tr>
            <th>Name</th>
            <th>Sortierung</th>
            <th>&nbsp;</th>
	    </tr>
    </thead>
	<?php
    foreach ($medals as $medal) {
        ?>
        <tr>
            <td><?php echo $this->escapeHtml($medal->name);?></td>
            <td><?php echo $this->escapeHtml($medal->sorting);?></td>
            <td>
                <a href="<?php echo $this->url('medalEdit', array('id' => $medal->id));?>">Bearbeiten</a>
            </td>
        </tr>
        <?php
    }
    ?>
</table>
