<?php
$title = 'Kurse';
$this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
    <a class="btn btn-success pull-right" href="<?php echo $this->url('workshopEdit', array('id' => 0));?>">Neuen Kurs hinzufügen</a>
</h1>

<table class="table table-striped table-hover">
    <thead>
	    <tr>
            <th>Name</th>
            <th>&nbsp;</th>
	    </tr>
    </thead>
	<?php
    foreach ($workshops as $workshop) {
        ?>
        <tr>
            <td><?php echo $this->escapeHtml($workshop->name);?></td>
            <td>
                <a href="<?php echo $this->url('workshopEdit', array('id' => $workshop->id));?>">Bearbeiten</a>
            </td>
        </tr>
        <?php
    }
    ?>
</table>
