<div class="jumbotron">
    <h1>Vereinsverwaltung</h1>
    <p>Blasmusik Königstetten</p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-group fa-fw"></i> Mitglieder</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('members'); ?>">Personenliste &raquo;</a></p>
                <p><a href="<?php echo $this->url('workshops'); ?>">Kurse &raquo;</a></p>
                <p><a href="<?php echo $this->url('medals'); ?>">Abzeichen &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-tags fa-fw"></i> Instrumente</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('instruments'); ?>">Instrumentenliste &raquo;</a></p>
                <p><a href="<?php echo $this->url('instrumentCategories'); ?>">Kategorien &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-music fa-fw"></i> Noten</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('sheetmusic'); ?>">Notenliste &raquo;</a></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-calendar fa-fw"></i> Termine</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('calendar'); ?>">Kalender &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-file fa-fw"></i> Dokumente</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('documents'); ?>">Dokumentenliste &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
