<div class="page-header">
    <h1><?php echo $this->customization('company_name'); ?> <small>Vereinsverwaltung</small></h1>
</div>

<div class="row">
    <?php if ($this->isAllowed('Members\Controller\Member')) { ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-group fa-fw"></i> Mitglieder</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('members'); ?>">Personenliste</a></p>
                <hr>
                <p><a href="<?php echo $this->url('workshops'); ?>">Kurse</a></p>
                <p><a href="<?php echo $this->url('medals'); ?>">Abzeichen</a></p>
            </div>
        </div>
    </div>
    <?php } ?>

    <?php if ($this->isAllowed('Attendance\Controller\Sheet')) { ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-table fa-fw"></i> Anwesenheit</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('attendance'); ?>">Anwesenheits-Listen</a></p>
                <hr>
                <p><a href="<?php echo $this->url('attendanceReport'); ?>">Auswertung</a></p>
            </div>
        </div>
    </div>
    <?php } ?>

    <?php if ($this->isAllowed('Instruments\Controller\Instrument')) { ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-tags fa-fw"></i> Instrumente</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('instruments'); ?>">Instrumentenliste</a></p>
                <hr>
                <p><a href="<?php echo $this->url('instrumentCategories'); ?>">Kategorien</a></p>
            </div>
        </div>
    </div>
    <?php } ?>
</div>

<div class="row">
    <?php if ($this->isAllowed('Sheetmusic\Controller\Sheetmusic')) { ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-music fa-fw"></i> Noten</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('sheetmusic'); ?>">Notenliste</a></p>
            </div>
        </div>
    </div>
    <?php } ?>

    <?php if ($this->isAllowed('Calendar\Controller\Calendar')) { ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-calendar fa-fw"></i> Termine</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('calendar'); ?>">Kalender</a></p>
            </div>
        </div>
    </div>
    <?php } ?>

    <?php if ($this->isAllowed('Documents\Controller\Document')) { ?>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-file fa-fw"></i> Dokumente</h3>
            </div>
            <div class="panel-body">
                <p><a href="<?php echo $this->url('documents'); ?>">Dokumentenliste</a></p>
            </div>
        </div>
    </div>
    <?php } ?>
</div>
